// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
