// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyDescriptionAttribute("A package of libraries for generic math types and advanced algorithms for game developments")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyCopyrightAttribute("Apache 2.0 License")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyDescription = "A package of libraries for generic math types and advanced algorithms for game developments"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyCopyright = "Apache 2.0 License"
